# frozen_string_literal: true

require "rails/generators/base"
require "net/http"
require "json"
require "uri"

module AgentE2e
  module Generators
    class TestSeedsGenerator < Rails::Generators::Base
      desc "Analyzes your models and generates db/test_seeds.rb using OpenAI"

      def generate_test_seeds
        model_files = Dir.glob(File.join(destination_root, "app/models/**/*.rb"))
        if model_files.empty?
          say "No models found in app/models/. Nothing to generate.", :yellow
          return
        end

        api_key = ENV["OPENAI_API_KEY"]
        dotenv_path = File.join(destination_root, ".env")
        if !api_key && File.exist?(dotenv_path)
          File.readlines(dotenv_path).each do |line|
            if line.strip.match?(/\AOPENAI_API_KEY=/)
              api_key = line.strip.sub("OPENAI_API_KEY=", "")
              break
            end
          end
        end

        unless api_key && !api_key.empty?
          say "OPENAI_API_KEY not found.", :red
          say ""
          say "Add it to your .env file and try again:", :yellow
          say "  echo 'OPENAI_API_KEY=sk-...' >> .env"
          say "  bin/rails generate agent_e2e:test_seeds"
          return
        end

        say "Found #{model_files.size} model(s). Analyzing...", :green

        schema_path = File.join(destination_root, "db/schema.rb")
        schema_content = File.exist?(schema_path) ? File.read(schema_path) : nil

        models_content = model_files.map { |f|
          relative = f.sub("#{destination_root}/", "")
          "# #{relative}\n#{File.read(f)}"
        }.join("\n\n")

        user_model = detect_user_model(model_files)

        prompt = build_seed_prompt(models_content, schema_content, user_model)
        ai_seeds = call_openai(api_key, prompt)

        if ai_seeds
          seeds_code = <<~RUBY
            # Auto-generated by agent_e2e:test_seeds

            #{ai_seeds}
          RUBY
          create_file "db/test_seeds.rb", seeds_code, force: true
          say ""
          say "Generated db/test_seeds.rb", :green
        else
          fallback = build_fallback_seeds(user_model, models_content)
          create_file "db/test_seeds.rb", fallback, force: true
          say ""
          say "Generated db/test_seeds.rb (fallback — AI generation failed)", :yellow
          say "WARNING: Review db/test_seeds.rb and add seeds for your models manually.", :yellow
        end
        say "Review it and run your tests with: bin/e2e", :cyan
      end

      private

      def detect_user_model(model_files)
        model_files.each do |f|
          content = File.read(f)
          basename = File.basename(f, ".rb")
          return basename.camelize if content.match?(/devise|has_secure_password|authenticate/i)
        end
        model_files.each do |f|
          basename = File.basename(f, ".rb")
          return basename.camelize if basename.match?(/\Auser\z|\Aaccount\z|\Aadmin\z/i)
        end
        "User"
      end

      def build_fallback_seeds(user_model, models_content)
        uses_devise = models_content.match?(/devise/)
        lines = []
        lines << "# Auto-generated by agent_e2e:test_seeds (fallback)"
        lines << "# AI generation failed — review and complete this file manually."
        lines << ""
        lines << "qa_user = #{user_model}.find_or_create_by!(email: \"qa@example.com\") do |u|"
        lines << "  u.password = \"Password123!\""
        lines << "  u.password_confirmation = \"Password123!\"" if uses_devise
        lines << "  u.confirmed_at = Time.current" if models_content.match?(/confirmable/i)
        lines << "  # TODO: add any other required fields for #{user_model}"
        lines << "end"
        lines << ""
        lines.join("\n")
      end

      def build_seed_prompt(models_content, schema_content, user_model)
        <<~PROMPT
          You are a Ruby on Rails expert. Analyze the following models and database schema,
          then generate seed data for end-to-end (E2E) browser testing.

          Requirements:
          - The FIRST thing in the output must be creating a QA user for E2E testing:
            * Model: #{user_model}
            * Email: qa@example.com
            * Password: Password123!
            * Assign the result to a variable called `qa_user`
            * Fill ALL required fields (from validations and null:false columns) with realistic values
            * If the model uses Devise, set password_confirmation and confirmed_at
          - Use `find_or_create_by!` to make the script idempotent (safe to run multiple times)
          - Create realistic sample data for ALL models, respecting associations and validations
          - Handle belongs_to associations by creating parent records first (topological order)
          - Include enough variety (at least 2-3 records per model where it makes sense)
          - Add brief comments explaining what each section seeds
          - Wrap everything in an ActiveRecord::Base.transaction block
          - Handle any enum values you find in the models
          - If there's a role/admin system, create an admin user (different from qa_user)
          - The data should be meaningful and realistic, not placeholder text
          - If models use Devise, handle `confirmed_at`, `password_confirmation`, etc.
          - If models have file attachments (ActiveStorage), skip those fields
          - Output ONLY valid Ruby code — no markdown fences, no explanations

          ## Models:

          #{models_content}

          #{schema_content ? "## Database Schema:\n\n#{schema_content}" : ""}

          Generate the seed code:
        PROMPT
      end

      def call_openai(api_key, prompt)
        model = ENV["SEED_AI_MODEL"] || "gpt-5.3-codex"
        uri = URI("https://api.openai.com/v1/responses")
        http = Net::HTTP.new(uri.host, uri.port)
        http.use_ssl = true
        http.read_timeout = 120

        request = Net::HTTP::Post.new(uri)
        request["Content-Type"] = "application/json"
        request["Authorization"] = "Bearer #{api_key}"

        request.body = JSON.generate({
          model: model,
          input: prompt
        })

        say "Calling #{model} (this may take a moment)...", :cyan
        response = http.request(request)

        if response.code.to_i == 200
          data = JSON.parse(response.body)
          extract_ruby_code(data["output_text"])
        else
          say "OpenAI API error (#{response.code}): #{response.body[0..300]}", :red
          nil
        end
      rescue => e
        say "Error calling OpenAI API: #{e.message}", :red
        nil
      end

      def extract_ruby_code(content)
        return nil if content.nil? || content.strip.empty?
        code = content.strip
        code = code.sub(/\A```ruby\n?/, "").sub(/\n?```\z/, "")
        code = code.sub(/\A```\n?/, "").sub(/\n?```\z/, "")
        code.strip + "\n"
      end
    end
  end
end
